---
version: '3.7'
services:
  bbugyi200.cldr:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cldr:delegated
    working_dir: /cldr
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
